name: baitapnhom_lehuynhkimthu_2280603175
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  google_mlkit_translation: ^0.11.0
  google_mlkit_text_recognition: ^0.12.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
